package org.fbi.sbs.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.sbs.repository.model.Acttbc;
import org.fbi.sbs.repository.model.ActtbcExample;

public interface ActtbcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS.ACTTBC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    int countByExample(ActtbcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS.ACTTBC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    int deleteByExample(ActtbcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS.ACTTBC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    int insert(Acttbc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS.ACTTBC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    int insertSelective(Acttbc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS.ACTTBC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    List<Acttbc> selectByExample(ActtbcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS.ACTTBC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    int updateByExampleSelective(@Param("record") Acttbc record, @Param("example") ActtbcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS.ACTTBC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    int updateByExample(@Param("record") Acttbc record, @Param("example") ActtbcExample example);
}