package org.fbi.sbs.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.fbi.sbs.repository.model.Acttmc;
import org.fbi.sbs.repository.model.ActtmcExample;

public interface ActtmcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS.ACTTMC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    int countByExample(ActtmcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS.ACTTMC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    int deleteByExample(ActtmcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS.ACTTMC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    int insert(Acttmc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS.ACTTMC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    int insertSelective(Acttmc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS.ACTTMC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    List<Acttmc> selectByExample(ActtmcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS.ACTTMC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    int updateByExampleSelective(@Param("record") Acttmc record, @Param("example") ActtmcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS.ACTTMC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    int updateByExample(@Param("record") Acttmc record, @Param("example") ActtmcExample example);

    @Select("SELECT COUNT(*) FROM ACTTMC WHERE TDBSRT = #{tdbsrt}")
    int countSameTbc(@Param("tdbsrt") String tdbsrt);
}