/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.fbi.sbs.online.code.txn88484.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Tia88484 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Tia88484\",\"namespace\":\"org.fbi.sbs.online.code.txn88484.domain\",\"fields\":[{\"name\":\"pastyp\",\"type\":\"string\"},{\"name\":\"inpflg\",\"type\":\"string\"},{\"name\":\"sbknum\",\"type\":\"string\"},{\"name\":\"wrkunt\",\"type\":\"string\"},{\"name\":\"stmadd\",\"type\":\"string\"},{\"name\":\"intnet\",\"type\":\"string\"},{\"name\":\"engnam\",\"type\":\"string\"},{\"name\":\"regadd\",\"type\":\"string\"},{\"name\":\"coradd\",\"type\":\"string\"},{\"name\":\"cusnam\",\"type\":\"string\"},{\"name\":\"funcde\",\"type\":\"string\"},{\"name\":\"begnum\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence pastyp;
  @Deprecated public java.lang.CharSequence inpflg;
  @Deprecated public java.lang.CharSequence sbknum;
  @Deprecated public java.lang.CharSequence wrkunt;
  @Deprecated public java.lang.CharSequence stmadd;
  @Deprecated public java.lang.CharSequence intnet;
  @Deprecated public java.lang.CharSequence engnam;
  @Deprecated public java.lang.CharSequence regadd;
  @Deprecated public java.lang.CharSequence coradd;
  @Deprecated public java.lang.CharSequence cusnam;
  @Deprecated public java.lang.CharSequence funcde;
  @Deprecated public java.lang.CharSequence begnum;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Tia88484() {}

  /**
   * All-args constructor.
   */
  public Tia88484(java.lang.CharSequence pastyp, java.lang.CharSequence inpflg, java.lang.CharSequence sbknum, java.lang.CharSequence wrkunt, java.lang.CharSequence stmadd, java.lang.CharSequence intnet, java.lang.CharSequence engnam, java.lang.CharSequence regadd, java.lang.CharSequence coradd, java.lang.CharSequence cusnam, java.lang.CharSequence funcde, java.lang.CharSequence begnum) {
    this.pastyp = pastyp;
    this.inpflg = inpflg;
    this.sbknum = sbknum;
    this.wrkunt = wrkunt;
    this.stmadd = stmadd;
    this.intnet = intnet;
    this.engnam = engnam;
    this.regadd = regadd;
    this.coradd = coradd;
    this.cusnam = cusnam;
    this.funcde = funcde;
    this.begnum = begnum;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return pastyp;
    case 1: return inpflg;
    case 2: return sbknum;
    case 3: return wrkunt;
    case 4: return stmadd;
    case 5: return intnet;
    case 6: return engnam;
    case 7: return regadd;
    case 8: return coradd;
    case 9: return cusnam;
    case 10: return funcde;
    case 11: return begnum;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: pastyp = (java.lang.CharSequence)value$; break;
    case 1: inpflg = (java.lang.CharSequence)value$; break;
    case 2: sbknum = (java.lang.CharSequence)value$; break;
    case 3: wrkunt = (java.lang.CharSequence)value$; break;
    case 4: stmadd = (java.lang.CharSequence)value$; break;
    case 5: intnet = (java.lang.CharSequence)value$; break;
    case 6: engnam = (java.lang.CharSequence)value$; break;
    case 7: regadd = (java.lang.CharSequence)value$; break;
    case 8: coradd = (java.lang.CharSequence)value$; break;
    case 9: cusnam = (java.lang.CharSequence)value$; break;
    case 10: funcde = (java.lang.CharSequence)value$; break;
    case 11: begnum = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'pastyp' field.
   */
  public java.lang.CharSequence getPastyp() {
    return pastyp;
  }

  /**
   * Sets the value of the 'pastyp' field.
   * @param value the value to set.
   */
  public void setPastyp(java.lang.CharSequence value) {
    this.pastyp = value;
  }

  /**
   * Gets the value of the 'inpflg' field.
   */
  public java.lang.CharSequence getInpflg() {
    return inpflg;
  }

  /**
   * Sets the value of the 'inpflg' field.
   * @param value the value to set.
   */
  public void setInpflg(java.lang.CharSequence value) {
    this.inpflg = value;
  }

  /**
   * Gets the value of the 'sbknum' field.
   */
  public java.lang.CharSequence getSbknum() {
    return sbknum;
  }

  /**
   * Sets the value of the 'sbknum' field.
   * @param value the value to set.
   */
  public void setSbknum(java.lang.CharSequence value) {
    this.sbknum = value;
  }

  /**
   * Gets the value of the 'wrkunt' field.
   */
  public java.lang.CharSequence getWrkunt() {
    return wrkunt;
  }

  /**
   * Sets the value of the 'wrkunt' field.
   * @param value the value to set.
   */
  public void setWrkunt(java.lang.CharSequence value) {
    this.wrkunt = value;
  }

  /**
   * Gets the value of the 'stmadd' field.
   */
  public java.lang.CharSequence getStmadd() {
    return stmadd;
  }

  /**
   * Sets the value of the 'stmadd' field.
   * @param value the value to set.
   */
  public void setStmadd(java.lang.CharSequence value) {
    this.stmadd = value;
  }

  /**
   * Gets the value of the 'intnet' field.
   */
  public java.lang.CharSequence getIntnet() {
    return intnet;
  }

  /**
   * Sets the value of the 'intnet' field.
   * @param value the value to set.
   */
  public void setIntnet(java.lang.CharSequence value) {
    this.intnet = value;
  }

  /**
   * Gets the value of the 'engnam' field.
   */
  public java.lang.CharSequence getEngnam() {
    return engnam;
  }

  /**
   * Sets the value of the 'engnam' field.
   * @param value the value to set.
   */
  public void setEngnam(java.lang.CharSequence value) {
    this.engnam = value;
  }

  /**
   * Gets the value of the 'regadd' field.
   */
  public java.lang.CharSequence getRegadd() {
    return regadd;
  }

  /**
   * Sets the value of the 'regadd' field.
   * @param value the value to set.
   */
  public void setRegadd(java.lang.CharSequence value) {
    this.regadd = value;
  }

  /**
   * Gets the value of the 'coradd' field.
   */
  public java.lang.CharSequence getCoradd() {
    return coradd;
  }

  /**
   * Sets the value of the 'coradd' field.
   * @param value the value to set.
   */
  public void setCoradd(java.lang.CharSequence value) {
    this.coradd = value;
  }

  /**
   * Gets the value of the 'cusnam' field.
   */
  public java.lang.CharSequence getCusnam() {
    return cusnam;
  }

  /**
   * Sets the value of the 'cusnam' field.
   * @param value the value to set.
   */
  public void setCusnam(java.lang.CharSequence value) {
    this.cusnam = value;
  }

  /**
   * Gets the value of the 'funcde' field.
   */
  public java.lang.CharSequence getFuncde() {
    return funcde;
  }

  /**
   * Sets the value of the 'funcde' field.
   * @param value the value to set.
   */
  public void setFuncde(java.lang.CharSequence value) {
    this.funcde = value;
  }

  /**
   * Gets the value of the 'begnum' field.
   */
  public java.lang.CharSequence getBegnum() {
    return begnum;
  }

  /**
   * Sets the value of the 'begnum' field.
   * @param value the value to set.
   */
  public void setBegnum(java.lang.CharSequence value) {
    this.begnum = value;
  }

  /** Creates a new Tia88484 RecordBuilder */
  public static org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder newBuilder() {
    return new org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder();
  }
  
  /** Creates a new Tia88484 RecordBuilder by copying an existing Builder */
  public static org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder newBuilder(org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder other) {
    return new org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder(other);
  }
  
  /** Creates a new Tia88484 RecordBuilder by copying an existing Tia88484 instance */
  public static org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder newBuilder(org.fbi.sbs.online.code.txn88484.domain.Tia88484 other) {
    return new org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder(other);
  }
  
  /**
   * RecordBuilder for Tia88484 instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Tia88484>
    implements org.apache.avro.data.RecordBuilder<Tia88484> {

    private java.lang.CharSequence pastyp;
    private java.lang.CharSequence inpflg;
    private java.lang.CharSequence sbknum;
    private java.lang.CharSequence wrkunt;
    private java.lang.CharSequence stmadd;
    private java.lang.CharSequence intnet;
    private java.lang.CharSequence engnam;
    private java.lang.CharSequence regadd;
    private java.lang.CharSequence coradd;
    private java.lang.CharSequence cusnam;
    private java.lang.CharSequence funcde;
    private java.lang.CharSequence begnum;

    /** Creates a new Builder */
    private Builder() {
      super(org.fbi.sbs.online.code.txn88484.domain.Tia88484.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.pastyp)) {
        this.pastyp = data().deepCopy(fields()[0].schema(), other.pastyp);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.inpflg)) {
        this.inpflg = data().deepCopy(fields()[1].schema(), other.inpflg);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.sbknum)) {
        this.sbknum = data().deepCopy(fields()[2].schema(), other.sbknum);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.wrkunt)) {
        this.wrkunt = data().deepCopy(fields()[3].schema(), other.wrkunt);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.stmadd)) {
        this.stmadd = data().deepCopy(fields()[4].schema(), other.stmadd);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.intnet)) {
        this.intnet = data().deepCopy(fields()[5].schema(), other.intnet);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.engnam)) {
        this.engnam = data().deepCopy(fields()[6].schema(), other.engnam);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.regadd)) {
        this.regadd = data().deepCopy(fields()[7].schema(), other.regadd);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.coradd)) {
        this.coradd = data().deepCopy(fields()[8].schema(), other.coradd);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.cusnam)) {
        this.cusnam = data().deepCopy(fields()[9].schema(), other.cusnam);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.funcde)) {
        this.funcde = data().deepCopy(fields()[10].schema(), other.funcde);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.begnum)) {
        this.begnum = data().deepCopy(fields()[11].schema(), other.begnum);
        fieldSetFlags()[11] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Tia88484 instance */
    private Builder(org.fbi.sbs.online.code.txn88484.domain.Tia88484 other) {
            super(org.fbi.sbs.online.code.txn88484.domain.Tia88484.SCHEMA$);
      if (isValidValue(fields()[0], other.pastyp)) {
        this.pastyp = data().deepCopy(fields()[0].schema(), other.pastyp);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.inpflg)) {
        this.inpflg = data().deepCopy(fields()[1].schema(), other.inpflg);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.sbknum)) {
        this.sbknum = data().deepCopy(fields()[2].schema(), other.sbknum);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.wrkunt)) {
        this.wrkunt = data().deepCopy(fields()[3].schema(), other.wrkunt);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.stmadd)) {
        this.stmadd = data().deepCopy(fields()[4].schema(), other.stmadd);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.intnet)) {
        this.intnet = data().deepCopy(fields()[5].schema(), other.intnet);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.engnam)) {
        this.engnam = data().deepCopy(fields()[6].schema(), other.engnam);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.regadd)) {
        this.regadd = data().deepCopy(fields()[7].schema(), other.regadd);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.coradd)) {
        this.coradd = data().deepCopy(fields()[8].schema(), other.coradd);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.cusnam)) {
        this.cusnam = data().deepCopy(fields()[9].schema(), other.cusnam);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.funcde)) {
        this.funcde = data().deepCopy(fields()[10].schema(), other.funcde);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.begnum)) {
        this.begnum = data().deepCopy(fields()[11].schema(), other.begnum);
        fieldSetFlags()[11] = true;
      }
    }

    /** Gets the value of the 'pastyp' field */
    public java.lang.CharSequence getPastyp() {
      return pastyp;
    }
    
    /** Sets the value of the 'pastyp' field */
    public org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder setPastyp(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.pastyp = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'pastyp' field has been set */
    public boolean hasPastyp() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'pastyp' field */
    public org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder clearPastyp() {
      pastyp = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'inpflg' field */
    public java.lang.CharSequence getInpflg() {
      return inpflg;
    }
    
    /** Sets the value of the 'inpflg' field */
    public org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder setInpflg(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.inpflg = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'inpflg' field has been set */
    public boolean hasInpflg() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'inpflg' field */
    public org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder clearInpflg() {
      inpflg = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'sbknum' field */
    public java.lang.CharSequence getSbknum() {
      return sbknum;
    }
    
    /** Sets the value of the 'sbknum' field */
    public org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder setSbknum(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.sbknum = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'sbknum' field has been set */
    public boolean hasSbknum() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'sbknum' field */
    public org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder clearSbknum() {
      sbknum = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'wrkunt' field */
    public java.lang.CharSequence getWrkunt() {
      return wrkunt;
    }
    
    /** Sets the value of the 'wrkunt' field */
    public org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder setWrkunt(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.wrkunt = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'wrkunt' field has been set */
    public boolean hasWrkunt() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'wrkunt' field */
    public org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder clearWrkunt() {
      wrkunt = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'stmadd' field */
    public java.lang.CharSequence getStmadd() {
      return stmadd;
    }
    
    /** Sets the value of the 'stmadd' field */
    public org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder setStmadd(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.stmadd = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'stmadd' field has been set */
    public boolean hasStmadd() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'stmadd' field */
    public org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder clearStmadd() {
      stmadd = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'intnet' field */
    public java.lang.CharSequence getIntnet() {
      return intnet;
    }
    
    /** Sets the value of the 'intnet' field */
    public org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder setIntnet(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.intnet = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'intnet' field has been set */
    public boolean hasIntnet() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'intnet' field */
    public org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder clearIntnet() {
      intnet = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'engnam' field */
    public java.lang.CharSequence getEngnam() {
      return engnam;
    }
    
    /** Sets the value of the 'engnam' field */
    public org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder setEngnam(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.engnam = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'engnam' field has been set */
    public boolean hasEngnam() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'engnam' field */
    public org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder clearEngnam() {
      engnam = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'regadd' field */
    public java.lang.CharSequence getRegadd() {
      return regadd;
    }
    
    /** Sets the value of the 'regadd' field */
    public org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder setRegadd(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.regadd = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'regadd' field has been set */
    public boolean hasRegadd() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'regadd' field */
    public org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder clearRegadd() {
      regadd = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'coradd' field */
    public java.lang.CharSequence getCoradd() {
      return coradd;
    }
    
    /** Sets the value of the 'coradd' field */
    public org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder setCoradd(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.coradd = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'coradd' field has been set */
    public boolean hasCoradd() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'coradd' field */
    public org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder clearCoradd() {
      coradd = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'cusnam' field */
    public java.lang.CharSequence getCusnam() {
      return cusnam;
    }
    
    /** Sets the value of the 'cusnam' field */
    public org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder setCusnam(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.cusnam = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'cusnam' field has been set */
    public boolean hasCusnam() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'cusnam' field */
    public org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder clearCusnam() {
      cusnam = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'funcde' field */
    public java.lang.CharSequence getFuncde() {
      return funcde;
    }
    
    /** Sets the value of the 'funcde' field */
    public org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder setFuncde(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.funcde = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'funcde' field has been set */
    public boolean hasFuncde() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'funcde' field */
    public org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder clearFuncde() {
      funcde = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'begnum' field */
    public java.lang.CharSequence getBegnum() {
      return begnum;
    }
    
    /** Sets the value of the 'begnum' field */
    public org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder setBegnum(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.begnum = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'begnum' field has been set */
    public boolean hasBegnum() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'begnum' field */
    public org.fbi.sbs.online.code.txn88484.domain.Tia88484.Builder clearBegnum() {
      begnum = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    public Tia88484 build() {
      try {
        Tia88484 record = new Tia88484();
        record.pastyp = fieldSetFlags()[0] ? this.pastyp : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.inpflg = fieldSetFlags()[1] ? this.inpflg : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.sbknum = fieldSetFlags()[2] ? this.sbknum : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.wrkunt = fieldSetFlags()[3] ? this.wrkunt : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.stmadd = fieldSetFlags()[4] ? this.stmadd : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.intnet = fieldSetFlags()[5] ? this.intnet : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.engnam = fieldSetFlags()[6] ? this.engnam : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.regadd = fieldSetFlags()[7] ? this.regadd : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.coradd = fieldSetFlags()[8] ? this.coradd : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.cusnam = fieldSetFlags()[9] ? this.cusnam : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.funcde = fieldSetFlags()[10] ? this.funcde : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.begnum = fieldSetFlags()[11] ? this.begnum : (java.lang.CharSequence) defaultValue(fields()[11]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
