/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.fbi.sbs.online.code.txn88481.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Tia88481 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Tia88481\",\"namespace\":\"org.fbi.sbs.online.code.txn88481.domain\",\"fields\":[{\"name\":\"begnum\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence begnum;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Tia88481() {}

  /**
   * All-args constructor.
   */
  public Tia88481(java.lang.CharSequence begnum) {
    this.begnum = begnum;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return begnum;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: begnum = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'begnum' field.
   */
  public java.lang.CharSequence getBegnum() {
    return begnum;
  }

  /**
   * Sets the value of the 'begnum' field.
   * @param value the value to set.
   */
  public void setBegnum(java.lang.CharSequence value) {
    this.begnum = value;
  }

  /** Creates a new Tia88481 RecordBuilder */
  public static org.fbi.sbs.online.code.txn88481.domain.Tia88481.Builder newBuilder() {
    return new org.fbi.sbs.online.code.txn88481.domain.Tia88481.Builder();
  }
  
  /** Creates a new Tia88481 RecordBuilder by copying an existing Builder */
  public static org.fbi.sbs.online.code.txn88481.domain.Tia88481.Builder newBuilder(org.fbi.sbs.online.code.txn88481.domain.Tia88481.Builder other) {
    return new org.fbi.sbs.online.code.txn88481.domain.Tia88481.Builder(other);
  }
  
  /** Creates a new Tia88481 RecordBuilder by copying an existing Tia88481 instance */
  public static org.fbi.sbs.online.code.txn88481.domain.Tia88481.Builder newBuilder(org.fbi.sbs.online.code.txn88481.domain.Tia88481 other) {
    return new org.fbi.sbs.online.code.txn88481.domain.Tia88481.Builder(other);
  }
  
  /**
   * RecordBuilder for Tia88481 instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Tia88481>
    implements org.apache.avro.data.RecordBuilder<Tia88481> {

    private java.lang.CharSequence begnum;

    /** Creates a new Builder */
    private Builder() {
      super(org.fbi.sbs.online.code.txn88481.domain.Tia88481.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.fbi.sbs.online.code.txn88481.domain.Tia88481.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.begnum)) {
        this.begnum = data().deepCopy(fields()[0].schema(), other.begnum);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Tia88481 instance */
    private Builder(org.fbi.sbs.online.code.txn88481.domain.Tia88481 other) {
            super(org.fbi.sbs.online.code.txn88481.domain.Tia88481.SCHEMA$);
      if (isValidValue(fields()[0], other.begnum)) {
        this.begnum = data().deepCopy(fields()[0].schema(), other.begnum);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'begnum' field */
    public java.lang.CharSequence getBegnum() {
      return begnum;
    }
    
    /** Sets the value of the 'begnum' field */
    public org.fbi.sbs.online.code.txn88481.domain.Tia88481.Builder setBegnum(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.begnum = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'begnum' field has been set */
    public boolean hasBegnum() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'begnum' field */
    public org.fbi.sbs.online.code.txn88481.domain.Tia88481.Builder clearBegnum() {
      begnum = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public Tia88481 build() {
      try {
        Tia88481 record = new Tia88481();
        record.begnum = fieldSetFlags()[0] ? this.begnum : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
