/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.fbi.sbs.online.code.txn88481.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Toa88481 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Toa88481\",\"namespace\":\"org.fbi.sbs.online.code.txn88481.domain\",\"fields\":[{\"name\":\"totcnt\",\"type\":\"string\"},{\"name\":\"infos\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"IndustryInfo\",\"fields\":[{\"name\":\"tddtdc\",\"type\":\"string\"},{\"name\":\"tddnam\",\"type\":\"string\"}],\"namespace:\":\"org.fbi.sbs.online.code.txn88481.domain\"}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence totcnt;
  @Deprecated public java.util.List<org.fbi.sbs.online.code.txn88481.domain.IndustryInfo> infos;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Toa88481() {}

  /**
   * All-args constructor.
   */
  public Toa88481(java.lang.CharSequence totcnt, java.util.List<org.fbi.sbs.online.code.txn88481.domain.IndustryInfo> infos) {
    this.totcnt = totcnt;
    this.infos = infos;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return totcnt;
    case 1: return infos;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: totcnt = (java.lang.CharSequence)value$; break;
    case 1: infos = (java.util.List<org.fbi.sbs.online.code.txn88481.domain.IndustryInfo>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'totcnt' field.
   */
  public java.lang.CharSequence getTotcnt() {
    return totcnt;
  }

  /**
   * Sets the value of the 'totcnt' field.
   * @param value the value to set.
   */
  public void setTotcnt(java.lang.CharSequence value) {
    this.totcnt = value;
  }

  /**
   * Gets the value of the 'infos' field.
   */
  public java.util.List<org.fbi.sbs.online.code.txn88481.domain.IndustryInfo> getInfos() {
    return infos;
  }

  /**
   * Sets the value of the 'infos' field.
   * @param value the value to set.
   */
  public void setInfos(java.util.List<org.fbi.sbs.online.code.txn88481.domain.IndustryInfo> value) {
    this.infos = value;
  }

  /** Creates a new Toa88481 RecordBuilder */
  public static org.fbi.sbs.online.code.txn88481.domain.Toa88481.Builder newBuilder() {
    return new org.fbi.sbs.online.code.txn88481.domain.Toa88481.Builder();
  }
  
  /** Creates a new Toa88481 RecordBuilder by copying an existing Builder */
  public static org.fbi.sbs.online.code.txn88481.domain.Toa88481.Builder newBuilder(org.fbi.sbs.online.code.txn88481.domain.Toa88481.Builder other) {
    return new org.fbi.sbs.online.code.txn88481.domain.Toa88481.Builder(other);
  }
  
  /** Creates a new Toa88481 RecordBuilder by copying an existing Toa88481 instance */
  public static org.fbi.sbs.online.code.txn88481.domain.Toa88481.Builder newBuilder(org.fbi.sbs.online.code.txn88481.domain.Toa88481 other) {
    return new org.fbi.sbs.online.code.txn88481.domain.Toa88481.Builder(other);
  }
  
  /**
   * RecordBuilder for Toa88481 instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Toa88481>
    implements org.apache.avro.data.RecordBuilder<Toa88481> {

    private java.lang.CharSequence totcnt;
    private java.util.List<org.fbi.sbs.online.code.txn88481.domain.IndustryInfo> infos;

    /** Creates a new Builder */
    private Builder() {
      super(org.fbi.sbs.online.code.txn88481.domain.Toa88481.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.fbi.sbs.online.code.txn88481.domain.Toa88481.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.totcnt)) {
        this.totcnt = data().deepCopy(fields()[0].schema(), other.totcnt);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.infos)) {
        this.infos = data().deepCopy(fields()[1].schema(), other.infos);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Toa88481 instance */
    private Builder(org.fbi.sbs.online.code.txn88481.domain.Toa88481 other) {
            super(org.fbi.sbs.online.code.txn88481.domain.Toa88481.SCHEMA$);
      if (isValidValue(fields()[0], other.totcnt)) {
        this.totcnt = data().deepCopy(fields()[0].schema(), other.totcnt);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.infos)) {
        this.infos = data().deepCopy(fields()[1].schema(), other.infos);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'totcnt' field */
    public java.lang.CharSequence getTotcnt() {
      return totcnt;
    }
    
    /** Sets the value of the 'totcnt' field */
    public org.fbi.sbs.online.code.txn88481.domain.Toa88481.Builder setTotcnt(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.totcnt = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'totcnt' field has been set */
    public boolean hasTotcnt() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'totcnt' field */
    public org.fbi.sbs.online.code.txn88481.domain.Toa88481.Builder clearTotcnt() {
      totcnt = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'infos' field */
    public java.util.List<org.fbi.sbs.online.code.txn88481.domain.IndustryInfo> getInfos() {
      return infos;
    }
    
    /** Sets the value of the 'infos' field */
    public org.fbi.sbs.online.code.txn88481.domain.Toa88481.Builder setInfos(java.util.List<org.fbi.sbs.online.code.txn88481.domain.IndustryInfo> value) {
      validate(fields()[1], value);
      this.infos = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'infos' field has been set */
    public boolean hasInfos() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'infos' field */
    public org.fbi.sbs.online.code.txn88481.domain.Toa88481.Builder clearInfos() {
      infos = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Toa88481 build() {
      try {
        Toa88481 record = new Toa88481();
        record.totcnt = fieldSetFlags()[0] ? this.totcnt : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.infos = fieldSetFlags()[1] ? this.infos : (java.util.List<org.fbi.sbs.online.code.txn88481.domain.IndustryInfo>) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
