/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.fbi.sbs.domain.toa;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class detail extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"detail\",\"namespace\":\"org.fbi.sbs.domain.toa\",\"fields\":[{\"name\":\"tddtdc\",\"type\":\"string\"},{\"name\":\"tddnam\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence tddtdc;
  @Deprecated public java.lang.CharSequence tddnam;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public detail() {}

  /**
   * All-args constructor.
   */
  public detail(java.lang.CharSequence tddtdc, java.lang.CharSequence tddnam) {
    this.tddtdc = tddtdc;
    this.tddnam = tddnam;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return tddtdc;
    case 1: return tddnam;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: tddtdc = (java.lang.CharSequence)value$; break;
    case 1: tddnam = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'tddtdc' field.
   */
  public java.lang.CharSequence getTddtdc() {
    return tddtdc;
  }

  /**
   * Sets the value of the 'tddtdc' field.
   * @param value the value to set.
   */
  public void setTddtdc(java.lang.CharSequence value) {
    this.tddtdc = value;
  }

  /**
   * Gets the value of the 'tddnam' field.
   */
  public java.lang.CharSequence getTddnam() {
    return tddnam;
  }

  /**
   * Sets the value of the 'tddnam' field.
   * @param value the value to set.
   */
  public void setTddnam(java.lang.CharSequence value) {
    this.tddnam = value;
  }

  /** Creates a new detail RecordBuilder */
  public static org.fbi.sbs.domain.toa.detail.Builder newBuilder() {
    return new org.fbi.sbs.domain.toa.detail.Builder();
  }
  
  /** Creates a new detail RecordBuilder by copying an existing Builder */
  public static org.fbi.sbs.domain.toa.detail.Builder newBuilder(org.fbi.sbs.domain.toa.detail.Builder other) {
    return new org.fbi.sbs.domain.toa.detail.Builder(other);
  }
  
  /** Creates a new detail RecordBuilder by copying an existing detail instance */
  public static org.fbi.sbs.domain.toa.detail.Builder newBuilder(org.fbi.sbs.domain.toa.detail other) {
    return new org.fbi.sbs.domain.toa.detail.Builder(other);
  }
  
  /**
   * RecordBuilder for detail instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<detail>
    implements org.apache.avro.data.RecordBuilder<detail> {

    private java.lang.CharSequence tddtdc;
    private java.lang.CharSequence tddnam;

    /** Creates a new Builder */
    private Builder() {
      super(org.fbi.sbs.domain.toa.detail.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.fbi.sbs.domain.toa.detail.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.tddtdc)) {
        this.tddtdc = data().deepCopy(fields()[0].schema(), other.tddtdc);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.tddnam)) {
        this.tddnam = data().deepCopy(fields()[1].schema(), other.tddnam);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing detail instance */
    private Builder(org.fbi.sbs.domain.toa.detail other) {
            super(org.fbi.sbs.domain.toa.detail.SCHEMA$);
      if (isValidValue(fields()[0], other.tddtdc)) {
        this.tddtdc = data().deepCopy(fields()[0].schema(), other.tddtdc);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.tddnam)) {
        this.tddnam = data().deepCopy(fields()[1].schema(), other.tddnam);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'tddtdc' field */
    public java.lang.CharSequence getTddtdc() {
      return tddtdc;
    }
    
    /** Sets the value of the 'tddtdc' field */
    public org.fbi.sbs.domain.toa.detail.Builder setTddtdc(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.tddtdc = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'tddtdc' field has been set */
    public boolean hasTddtdc() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'tddtdc' field */
    public org.fbi.sbs.domain.toa.detail.Builder clearTddtdc() {
      tddtdc = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'tddnam' field */
    public java.lang.CharSequence getTddnam() {
      return tddnam;
    }
    
    /** Sets the value of the 'tddnam' field */
    public org.fbi.sbs.domain.toa.detail.Builder setTddnam(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.tddnam = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'tddnam' field has been set */
    public boolean hasTddnam() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'tddnam' field */
    public org.fbi.sbs.domain.toa.detail.Builder clearTddnam() {
      tddnam = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public detail build() {
      try {
        detail record = new detail();
        record.tddtdc = fieldSetFlags()[0] ? this.tddtdc : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.tddnam = fieldSetFlags()[1] ? this.tddnam : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
