/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.fbi.sbs.domain.toa;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Toa909 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Toa909\",\"namespace\":\"org.fbi.sbs.domain.toa\",\"fields\":[{\"name\":\"totcnt\",\"type\":\"string\"},{\"name\":\"details\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"detail\",\"fields\":[{\"name\":\"tddtdc\",\"type\":\"string\"},{\"name\":\"tddnam\",\"type\":\"string\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence totcnt;
  @Deprecated public java.util.List<org.fbi.sbs.domain.toa.detail> details;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Toa909() {}

  /**
   * All-args constructor.
   */
  public Toa909(java.lang.CharSequence totcnt, java.util.List<org.fbi.sbs.domain.toa.detail> details) {
    this.totcnt = totcnt;
    this.details = details;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return totcnt;
    case 1: return details;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: totcnt = (java.lang.CharSequence)value$; break;
    case 1: details = (java.util.List<org.fbi.sbs.domain.toa.detail>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'totcnt' field.
   */
  public java.lang.CharSequence getTotcnt() {
    return totcnt;
  }

  /**
   * Sets the value of the 'totcnt' field.
   * @param value the value to set.
   */
  public void setTotcnt(java.lang.CharSequence value) {
    this.totcnt = value;
  }

  /**
   * Gets the value of the 'details' field.
   */
  public java.util.List<org.fbi.sbs.domain.toa.detail> getDetails() {
    return details;
  }

  /**
   * Sets the value of the 'details' field.
   * @param value the value to set.
   */
  public void setDetails(java.util.List<org.fbi.sbs.domain.toa.detail> value) {
    this.details = value;
  }

  /** Creates a new Toa909 RecordBuilder */
  public static org.fbi.sbs.domain.toa.Toa909.Builder newBuilder() {
    return new org.fbi.sbs.domain.toa.Toa909.Builder();
  }
  
  /** Creates a new Toa909 RecordBuilder by copying an existing Builder */
  public static org.fbi.sbs.domain.toa.Toa909.Builder newBuilder(org.fbi.sbs.domain.toa.Toa909.Builder other) {
    return new org.fbi.sbs.domain.toa.Toa909.Builder(other);
  }
  
  /** Creates a new Toa909 RecordBuilder by copying an existing Toa909 instance */
  public static org.fbi.sbs.domain.toa.Toa909.Builder newBuilder(org.fbi.sbs.domain.toa.Toa909 other) {
    return new org.fbi.sbs.domain.toa.Toa909.Builder(other);
  }
  
  /**
   * RecordBuilder for Toa909 instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Toa909>
    implements org.apache.avro.data.RecordBuilder<Toa909> {

    private java.lang.CharSequence totcnt;
    private java.util.List<org.fbi.sbs.domain.toa.detail> details;

    /** Creates a new Builder */
    private Builder() {
      super(org.fbi.sbs.domain.toa.Toa909.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.fbi.sbs.domain.toa.Toa909.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.totcnt)) {
        this.totcnt = data().deepCopy(fields()[0].schema(), other.totcnt);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.details)) {
        this.details = data().deepCopy(fields()[1].schema(), other.details);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Toa909 instance */
    private Builder(org.fbi.sbs.domain.toa.Toa909 other) {
            super(org.fbi.sbs.domain.toa.Toa909.SCHEMA$);
      if (isValidValue(fields()[0], other.totcnt)) {
        this.totcnt = data().deepCopy(fields()[0].schema(), other.totcnt);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.details)) {
        this.details = data().deepCopy(fields()[1].schema(), other.details);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'totcnt' field */
    public java.lang.CharSequence getTotcnt() {
      return totcnt;
    }
    
    /** Sets the value of the 'totcnt' field */
    public org.fbi.sbs.domain.toa.Toa909.Builder setTotcnt(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.totcnt = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'totcnt' field has been set */
    public boolean hasTotcnt() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'totcnt' field */
    public org.fbi.sbs.domain.toa.Toa909.Builder clearTotcnt() {
      totcnt = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'details' field */
    public java.util.List<org.fbi.sbs.domain.toa.detail> getDetails() {
      return details;
    }
    
    /** Sets the value of the 'details' field */
    public org.fbi.sbs.domain.toa.Toa909.Builder setDetails(java.util.List<org.fbi.sbs.domain.toa.detail> value) {
      validate(fields()[1], value);
      this.details = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'details' field has been set */
    public boolean hasDetails() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'details' field */
    public org.fbi.sbs.domain.toa.Toa909.Builder clearDetails() {
      details = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Toa909 build() {
      try {
        Toa909 record = new Toa909();
        record.totcnt = fieldSetFlags()[0] ? this.totcnt : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.details = fieldSetFlags()[1] ? this.details : (java.util.List<org.fbi.sbs.domain.toa.detail>) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
