package org.fbi.sbs.repository.model;

import java.util.Date;

public class Acttsc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SBS.ACTTSC.TDDTDC
     *
     * @mbggenerated Thu Apr 10 10:56:27 CST 2014
     */
    private String tddtdc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SBS.ACTTSC.TDDNAM
     *
     * @mbggenerated Thu Apr 10 10:56:27 CST 2014
     */
    private String tddnam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SBS.ACTTSC.TDDCN1
     *
     * @mbggenerated Thu Apr 10 10:56:27 CST 2014
     */
    private String tddcn1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SBS.ACTTSC.TDDCN2
     *
     * @mbggenerated Thu Apr 10 10:56:27 CST 2014
     */
    private String tddcn2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SBS.ACTTSC.TDDCN3
     *
     * @mbggenerated Thu Apr 10 10:56:27 CST 2014
     */
    private String tddcn3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SBS.ACTTSC.TDDCN4
     *
     * @mbggenerated Thu Apr 10 10:56:27 CST 2014
     */
    private String tddcn4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SBS.ACTTSC.AMDTLR
     *
     * @mbggenerated Thu Apr 10 10:56:27 CST 2014
     */
    private String amdtlr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SBS.ACTTSC.UPDDAT
     *
     * @mbggenerated Thu Apr 10 10:56:27 CST 2014
     */
    private Date upddat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SBS.ACTTSC.TDDTDC
     *
     * @return the value of SBS.ACTTSC.TDDTDC
     *
     * @mbggenerated Thu Apr 10 10:56:27 CST 2014
     */
    public String getTddtdc() {
        return tddtdc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SBS.ACTTSC.TDDTDC
     *
     * @param tddtdc the value for SBS.ACTTSC.TDDTDC
     *
     * @mbggenerated Thu Apr 10 10:56:27 CST 2014
     */
    public void setTddtdc(String tddtdc) {
        this.tddtdc = tddtdc == null ? null : tddtdc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SBS.ACTTSC.TDDNAM
     *
     * @return the value of SBS.ACTTSC.TDDNAM
     *
     * @mbggenerated Thu Apr 10 10:56:27 CST 2014
     */
    public String getTddnam() {
        return tddnam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SBS.ACTTSC.TDDNAM
     *
     * @param tddnam the value for SBS.ACTTSC.TDDNAM
     *
     * @mbggenerated Thu Apr 10 10:56:27 CST 2014
     */
    public void setTddnam(String tddnam) {
        this.tddnam = tddnam == null ? null : tddnam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SBS.ACTTSC.TDDCN1
     *
     * @return the value of SBS.ACTTSC.TDDCN1
     *
     * @mbggenerated Thu Apr 10 10:56:27 CST 2014
     */
    public String getTddcn1() {
        return tddcn1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SBS.ACTTSC.TDDCN1
     *
     * @param tddcn1 the value for SBS.ACTTSC.TDDCN1
     *
     * @mbggenerated Thu Apr 10 10:56:27 CST 2014
     */
    public void setTddcn1(String tddcn1) {
        this.tddcn1 = tddcn1 == null ? null : tddcn1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SBS.ACTTSC.TDDCN2
     *
     * @return the value of SBS.ACTTSC.TDDCN2
     *
     * @mbggenerated Thu Apr 10 10:56:27 CST 2014
     */
    public String getTddcn2() {
        return tddcn2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SBS.ACTTSC.TDDCN2
     *
     * @param tddcn2 the value for SBS.ACTTSC.TDDCN2
     *
     * @mbggenerated Thu Apr 10 10:56:27 CST 2014
     */
    public void setTddcn2(String tddcn2) {
        this.tddcn2 = tddcn2 == null ? null : tddcn2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SBS.ACTTSC.TDDCN3
     *
     * @return the value of SBS.ACTTSC.TDDCN3
     *
     * @mbggenerated Thu Apr 10 10:56:27 CST 2014
     */
    public String getTddcn3() {
        return tddcn3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SBS.ACTTSC.TDDCN3
     *
     * @param tddcn3 the value for SBS.ACTTSC.TDDCN3
     *
     * @mbggenerated Thu Apr 10 10:56:27 CST 2014
     */
    public void setTddcn3(String tddcn3) {
        this.tddcn3 = tddcn3 == null ? null : tddcn3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SBS.ACTTSC.TDDCN4
     *
     * @return the value of SBS.ACTTSC.TDDCN4
     *
     * @mbggenerated Thu Apr 10 10:56:27 CST 2014
     */
    public String getTddcn4() {
        return tddcn4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SBS.ACTTSC.TDDCN4
     *
     * @param tddcn4 the value for SBS.ACTTSC.TDDCN4
     *
     * @mbggenerated Thu Apr 10 10:56:27 CST 2014
     */
    public void setTddcn4(String tddcn4) {
        this.tddcn4 = tddcn4 == null ? null : tddcn4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SBS.ACTTSC.AMDTLR
     *
     * @return the value of SBS.ACTTSC.AMDTLR
     *
     * @mbggenerated Thu Apr 10 10:56:27 CST 2014
     */
    public String getAmdtlr() {
        return amdtlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SBS.ACTTSC.AMDTLR
     *
     * @param amdtlr the value for SBS.ACTTSC.AMDTLR
     *
     * @mbggenerated Thu Apr 10 10:56:27 CST 2014
     */
    public void setAmdtlr(String amdtlr) {
        this.amdtlr = amdtlr == null ? null : amdtlr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SBS.ACTTSC.UPDDAT
     *
     * @return the value of SBS.ACTTSC.UPDDAT
     *
     * @mbggenerated Thu Apr 10 10:56:27 CST 2014
     */
    public Date getUpddat() {
        return upddat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SBS.ACTTSC.UPDDAT
     *
     * @param upddat the value for SBS.ACTTSC.UPDDAT
     *
     * @mbggenerated Thu Apr 10 10:56:27 CST 2014
     */
    public void setUpddat(Date upddat) {
        this.upddat = upddat;
    }
}