package org.fbi.sbs.repository.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ActtbcExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SBS.ACTTBC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SBS.ACTTBC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SBS.ACTTBC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS.ACTTBC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    public ActtbcExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS.ACTTBC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS.ACTTBC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS.ACTTBC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS.ACTTBC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS.ACTTBC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS.ACTTBC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS.ACTTBC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS.ACTTBC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS.ACTTBC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS.ACTTBC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SBS.ACTTBC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTdbsrtIsNull() {
            addCriterion("TDBSRT is null");
            return (Criteria) this;
        }

        public Criteria andTdbsrtIsNotNull() {
            addCriterion("TDBSRT is not null");
            return (Criteria) this;
        }

        public Criteria andTdbsrtEqualTo(String value) {
            addCriterion("TDBSRT =", value, "tdbsrt");
            return (Criteria) this;
        }

        public Criteria andTdbsrtNotEqualTo(String value) {
            addCriterion("TDBSRT <>", value, "tdbsrt");
            return (Criteria) this;
        }

        public Criteria andTdbsrtGreaterThan(String value) {
            addCriterion("TDBSRT >", value, "tdbsrt");
            return (Criteria) this;
        }

        public Criteria andTdbsrtGreaterThanOrEqualTo(String value) {
            addCriterion("TDBSRT >=", value, "tdbsrt");
            return (Criteria) this;
        }

        public Criteria andTdbsrtLessThan(String value) {
            addCriterion("TDBSRT <", value, "tdbsrt");
            return (Criteria) this;
        }

        public Criteria andTdbsrtLessThanOrEqualTo(String value) {
            addCriterion("TDBSRT <=", value, "tdbsrt");
            return (Criteria) this;
        }

        public Criteria andTdbsrtLike(String value) {
            addCriterion("TDBSRT like", value, "tdbsrt");
            return (Criteria) this;
        }

        public Criteria andTdbsrtNotLike(String value) {
            addCriterion("TDBSRT not like", value, "tdbsrt");
            return (Criteria) this;
        }

        public Criteria andTdbsrtIn(List<String> values) {
            addCriterion("TDBSRT in", values, "tdbsrt");
            return (Criteria) this;
        }

        public Criteria andTdbsrtNotIn(List<String> values) {
            addCriterion("TDBSRT not in", values, "tdbsrt");
            return (Criteria) this;
        }

        public Criteria andTdbsrtBetween(String value1, String value2) {
            addCriterion("TDBSRT between", value1, value2, "tdbsrt");
            return (Criteria) this;
        }

        public Criteria andTdbsrtNotBetween(String value1, String value2) {
            addCriterion("TDBSRT not between", value1, value2, "tdbsrt");
            return (Criteria) this;
        }

        public Criteria andTdbnamIsNull() {
            addCriterion("TDBNAM is null");
            return (Criteria) this;
        }

        public Criteria andTdbnamIsNotNull() {
            addCriterion("TDBNAM is not null");
            return (Criteria) this;
        }

        public Criteria andTdbnamEqualTo(String value) {
            addCriterion("TDBNAM =", value, "tdbnam");
            return (Criteria) this;
        }

        public Criteria andTdbnamNotEqualTo(String value) {
            addCriterion("TDBNAM <>", value, "tdbnam");
            return (Criteria) this;
        }

        public Criteria andTdbnamGreaterThan(String value) {
            addCriterion("TDBNAM >", value, "tdbnam");
            return (Criteria) this;
        }

        public Criteria andTdbnamGreaterThanOrEqualTo(String value) {
            addCriterion("TDBNAM >=", value, "tdbnam");
            return (Criteria) this;
        }

        public Criteria andTdbnamLessThan(String value) {
            addCriterion("TDBNAM <", value, "tdbnam");
            return (Criteria) this;
        }

        public Criteria andTdbnamLessThanOrEqualTo(String value) {
            addCriterion("TDBNAM <=", value, "tdbnam");
            return (Criteria) this;
        }

        public Criteria andTdbnamLike(String value) {
            addCriterion("TDBNAM like", value, "tdbnam");
            return (Criteria) this;
        }

        public Criteria andTdbnamNotLike(String value) {
            addCriterion("TDBNAM not like", value, "tdbnam");
            return (Criteria) this;
        }

        public Criteria andTdbnamIn(List<String> values) {
            addCriterion("TDBNAM in", values, "tdbnam");
            return (Criteria) this;
        }

        public Criteria andTdbnamNotIn(List<String> values) {
            addCriterion("TDBNAM not in", values, "tdbnam");
            return (Criteria) this;
        }

        public Criteria andTdbnamBetween(String value1, String value2) {
            addCriterion("TDBNAM between", value1, value2, "tdbnam");
            return (Criteria) this;
        }

        public Criteria andTdbnamNotBetween(String value1, String value2) {
            addCriterion("TDBNAM not between", value1, value2, "tdbnam");
            return (Criteria) this;
        }

        public Criteria andAmdtlrIsNull() {
            addCriterion("AMDTLR is null");
            return (Criteria) this;
        }

        public Criteria andAmdtlrIsNotNull() {
            addCriterion("AMDTLR is not null");
            return (Criteria) this;
        }

        public Criteria andAmdtlrEqualTo(String value) {
            addCriterion("AMDTLR =", value, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrNotEqualTo(String value) {
            addCriterion("AMDTLR <>", value, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrGreaterThan(String value) {
            addCriterion("AMDTLR >", value, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrGreaterThanOrEqualTo(String value) {
            addCriterion("AMDTLR >=", value, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrLessThan(String value) {
            addCriterion("AMDTLR <", value, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrLessThanOrEqualTo(String value) {
            addCriterion("AMDTLR <=", value, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrLike(String value) {
            addCriterion("AMDTLR like", value, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrNotLike(String value) {
            addCriterion("AMDTLR not like", value, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrIn(List<String> values) {
            addCriterion("AMDTLR in", values, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrNotIn(List<String> values) {
            addCriterion("AMDTLR not in", values, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrBetween(String value1, String value2) {
            addCriterion("AMDTLR between", value1, value2, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrNotBetween(String value1, String value2) {
            addCriterion("AMDTLR not between", value1, value2, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andUpddatIsNull() {
            addCriterion("UPDDAT is null");
            return (Criteria) this;
        }

        public Criteria andUpddatIsNotNull() {
            addCriterion("UPDDAT is not null");
            return (Criteria) this;
        }

        public Criteria andUpddatEqualTo(Date value) {
            addCriterion("UPDDAT =", value, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatNotEqualTo(Date value) {
            addCriterion("UPDDAT <>", value, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatGreaterThan(Date value) {
            addCriterion("UPDDAT >", value, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDDAT >=", value, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatLessThan(Date value) {
            addCriterion("UPDDAT <", value, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatLessThanOrEqualTo(Date value) {
            addCriterion("UPDDAT <=", value, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatIn(List<Date> values) {
            addCriterion("UPDDAT in", values, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatNotIn(List<Date> values) {
            addCriterion("UPDDAT not in", values, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatBetween(Date value1, Date value2) {
            addCriterion("UPDDAT between", value1, value2, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatNotBetween(Date value1, Date value2) {
            addCriterion("UPDDAT not between", value1, value2, "upddat");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SBS.ACTTBC
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 10 13:36:10 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SBS.ACTTBC
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}