package org.fbi.sbs.repository.model;

import java.util.Date;

public class Acttmc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SBS.ACTTMC.TDBSRT
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    private String tdbsrt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SBS.ACTTMC.TDMSRT
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    private String tdmsrt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SBS.ACTTMC.TDMNAM
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    private String tdmnam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SBS.ACTTMC.AMDTLR
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    private String amdtlr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SBS.ACTTMC.UPDDAT
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    private Date upddat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SBS.ACTTMC.TDBSRT
     *
     * @return the value of SBS.ACTTMC.TDBSRT
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    public String getTdbsrt() {
        return tdbsrt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SBS.ACTTMC.TDBSRT
     *
     * @param tdbsrt the value for SBS.ACTTMC.TDBSRT
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    public void setTdbsrt(String tdbsrt) {
        this.tdbsrt = tdbsrt == null ? null : tdbsrt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SBS.ACTTMC.TDMSRT
     *
     * @return the value of SBS.ACTTMC.TDMSRT
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    public String getTdmsrt() {
        return tdmsrt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SBS.ACTTMC.TDMSRT
     *
     * @param tdmsrt the value for SBS.ACTTMC.TDMSRT
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    public void setTdmsrt(String tdmsrt) {
        this.tdmsrt = tdmsrt == null ? null : tdmsrt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SBS.ACTTMC.TDMNAM
     *
     * @return the value of SBS.ACTTMC.TDMNAM
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    public String getTdmnam() {
        return tdmnam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SBS.ACTTMC.TDMNAM
     *
     * @param tdmnam the value for SBS.ACTTMC.TDMNAM
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    public void setTdmnam(String tdmnam) {
        this.tdmnam = tdmnam == null ? null : tdmnam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SBS.ACTTMC.AMDTLR
     *
     * @return the value of SBS.ACTTMC.AMDTLR
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    public String getAmdtlr() {
        return amdtlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SBS.ACTTMC.AMDTLR
     *
     * @param amdtlr the value for SBS.ACTTMC.AMDTLR
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    public void setAmdtlr(String amdtlr) {
        this.amdtlr = amdtlr == null ? null : amdtlr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SBS.ACTTMC.UPDDAT
     *
     * @return the value of SBS.ACTTMC.UPDDAT
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    public Date getUpddat() {
        return upddat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SBS.ACTTMC.UPDDAT
     *
     * @param upddat the value for SBS.ACTTMC.UPDDAT
     *
     * @mbggenerated Thu Apr 10 13:36:10 CST 2014
     */
    public void setUpddat(Date upddat) {
        this.upddat = upddat;
    }
}